name: integration
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: handson github actions
        id: handson_github_actions
        uses: ks6088ts/handson-github-actions@main
        with:
          number: 1
          description: "v${{ github.run_id }}"
      - name: Check outputs
        run: |
          echo "${{ steps.handson_github_actions.outputs.number }}"
